declare interface IMedication {
  SUBSTÂNCIA : string;
  CNPJ : string;
  LABORATÓRIO : string;
  'CÓDIGO GGREM' : string;
  REGISTRO : string;
  'EAN 1' : string;
  'EAN 2' : string;
  'EAN 3' : string;
  PRODUTO : string;
  APRESENTAÇÃO : string;
  'CLASSE TERAPÊUTICA' : string;
  'TIPO DE PRODUTO (STATUS DO PRODUTO)' : string;
  'REGIME DE PREÇO' : string;
  'PF Sem Impostos' : string;
  'PF 0%' : string;
  'PF 12%' : string;
  'PF 17%': string;
  'PF 17% ALC' : string;
  'PF 17,5%': string;
  'PF 17,5% ALC' : string;
  'PF 18%' : string;
  'PF 18% ALC' : string;
  'PF 20%' : string;
  'PMC 0%' : string;
  'PMC 12%' : string;
  'PMC 17%' : string;
  'PMC 17% ALC' : string;
  'PMC 17,5%' : string;
  'PMC 17,5% ALC' : string;
  'PMC 18%' : string;
  'PMC 18% ALC' : string;
  'PMC 20%' : string;
  'RESTRIÇÃO HOSPITALAR' : string;
  CAP : string;
  'CONFAZ 87' : string;
  'ICMS 0%' : string;
  'ANÁLISE RECURSAL' : string;
  'LISTA DE CONCESSÃO DE CRÉDITO TRIBUTÁRIO (PIS/COFINS)' : string;
  'COMERCIALIZAÇÃO 2019' : string;
  TARJA : string;
}
